medgelabs:
  channelId: 62232210
  greeter:
    messageFormat: "Welcome to the lab, @{{.Sender}}!"
  channelPoints:
    messageFormat: "Thanks for the research @{{.Sender}}!"
  raid:
    messageFormat: "!so @{{.Sender}}"
  bits:
    messageFormat: "@{{.Sender}} gave {{.Amount}} hours of research to the Lab!"
  subs:
    messageFormat: "Thank you for {{.Amount}} months in the Lab, @{{.Sender}}!"
  giftsubs:
    messageFormat: "@{{.Sender}} loaned their lab coat to @{{.Recipient}}!"
sorceryandsarcasm:
  channelId: 66490190
  greeter:
    messageFormat: "@{{.Sender}} sorcer19Hype"
  raid:
    delaySeconds: 2
    messageFormat: "!so @{{.Sender}}"
spookyghostmachine:
  channelId: 119432399
  greeter:
    messageFormat: "@{{.Sender}} spooky127Hype"
  raid:
    messageFormat: "!so @{{.Sender}}"
  bits:
    messageFormat: "Thank you for the {{.Amount}} bittys @{{.Sender}}!"
