# Note for messageFormat:
#   subs: months first (%d), then subscriber (%s)
#   giftsubs: sender first (%s), then recipient (%s)
medgelabs:
  channelId: 62232210
  greeter:
    messageFormat: "Welcome to the lab, @%s!"
  channelPoints:
    messageFormat: "Thanks for the research @%s!"
  raid:
    messageFormat: "!so @%s"
  bits:
    messageFormat: "@{{.Sender}} gave {{.Amount}} hours of research to the Lab!"
  subs:
    messageFormat: "Thank you for %d months in the Lab, @%s!"
  giftsubs:
    messageFormat: "@%s loaned their lab coat to @%s!"
sorceryandsarcasm:
  channelId: 66490190
  greeter:
    messageFormat: "@%s sorcer19Hype"
  raid:
    messageFormat: "!so @%s"
  bits:
    messageFormat: "Thank you for the bits @%s!"
spookyghostmachine:
  channelId: 119432399
  greeter:
    messageFormat: "@%s spooky127Hype"
  raid:
    messageFormat: "!so @%s"
  bits:
    messageFormat: "Thank you for the bittys @%s!"
